version: '3.8'
services:
  postgres_account:
    image: postgres:15
    container_name: postgres_account
    environment:
      POSTGRES_USER: account_db
      POSTGRES_PASSWORD: account_db
      POSTGRES_DB: account_db
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: transaction_db
      MONGO_INITDB_ROOT_PASSWORD: transaction_db

  account-service:
    build:
      context: ./account
      dockerfile: Dockerfile
    container_name: account-service
    depends_on:
      - postgres_account
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_account:5432/account_db
      SPRING_DATASOURCE_USERNAME: account_db
      SPRING_DATASOURCE_PASSWORD: account_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  transaction-service:
    build:
      context: ./transaction
      dockerfile: Dockerfile
    container_name: transaction-service
    depends_on:
      - mongodb
      - kafka
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://transaction_db:transaction_db@mongodb:27017/transaction_db?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

volumes:
  postgres_data:
